name: config_runner
description: "generate configuration files for your project"
version: 0.0.2
homepage: https://github.com/samrat19/config_runner
repository: https://github.com/samrat19/config_runner

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  config:
