name: config_runner
description: "A powerful Dart CLI tool to streamline Flutter project setup by automating the creation of essential configuration and feature module boilerplate."
version: 0.0.7
homepage: https://github.com/samrat19/config_runner
repository: https://github.com/samrat19/config_runner

topics:
  - flutter
  - cli
  - codegen
  - environment
  - injectable

platforms:
  android:
  ios:
  macos:
  windows:
  linux:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  config: lib/bin/config.dart
